language: go

go:
  - tip # The latest version of Go.

install: true

env:
  global:
    - MYAPP=http-checker
    - MYEMAIL=dev@dev.dev
    - secure: ${GH_TOKEN}

before_install:
  - sudo apt-get -qq update
  - mkdir -p ${GOPATH}/bin

install:
  - go get -u github.com/F1NaL/$MYAPP
  - cd $GOPATH/src/github.com/F1NaL/$MYAPP
  - go install

script: echo "pass"

# build the app,build the package
before_deploy:
  - mkdir -p build/{386,amd64}
  - GOOS=linux GOARCH=386 go build --ldflags "-X main.version=${TRAVIS_TAG} -X main.build=${TRAVIS_BUILD_NUMBER} -X main.commit=${TRAVIS_COMMIT} -X main.docs=https://github.com/OrlovEvgeny/TinyJPG/blob/master/README.md" -o build/386/${MYAPP}-386 *.go
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.version=${TRAVIS_TAG} -X main.build=${TRAVIS_BUILD_NUMBER} -X main.commit=${TRAVIS_COMMIT} -X main.docs=https://github.com/OrlovEvgeny/TinyJPG/blob/master/README.md" -o build/amd64/${MYAPP}-amd64 *.go

deploy:
  provider: releases
  email: dev@dev.dev
  api_key:
    secure: ${GH_TOKEN}
  file:
    - build/386/${MYAPP}-386
    - build/amd64/${MYAPP}-amd64
  skip_cleanup: true
  on:
    tags: true
    all_branches: true